# admin web interfaces for management
version: '3'
services:

  # adminmongo:
  #   image: mrvautin/adminmongo
  #   ports:
  #     - 1234:1234
  #   environment:
  #     CONN_NAME: Local connection
  #     DB_HOST: your_mongodb_service
  #     DB_PORT: 27017

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./kui/config.yml:/config.yml
    networks:
      - message-broker_kafka-network
  
networks:
  message-broker_kafka-network:
    external: true